# Generated by Django 5.1.6 on 2025-03-03 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой')], max_length=10, verbose_name='Пол')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона (по желанию)')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('education_level', models.CharField(choices=[('secondary', 'Среднее'), ('higher', 'Высшее'), ('postgraduate', 'Послевузовское'), ('other', 'Другое')], max_length=20, verbose_name='Уровень образования')),
                ('other_education', models.CharField(blank=True, max_length=100, null=True, verbose_name='Другое образование')),
                ('profession', models.CharField(max_length=100, verbose_name='Ваша профессия')),
                ('workplace', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место работы (по желанию)')),
                ('smokes', models.BooleanField(default=False, verbose_name='Курите ли вы?')),
                ('drinks_alcohol', models.BooleanField(default=False, verbose_name='Употребляете ли вы алкоголь?')),
                ('stress_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Уровень стресса')),
                ('goals', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цели регистрации')),
                ('consent', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('additional_comments', models.TextField(blank=True, null=True, verbose_name='Дополнительные комментарии')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.FloatField(verbose_name='Результат')),
                ('description', models.TextField(verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.user')),
            ],
        ),
    ]
